title: Antonia Marcheva
logo: /assets/img/image.jpg
description: Hi, I'm Toni!
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme
remote_theme: pages-themes/minimal@v0.2.0
